CARDIR = carlib

car2: main.cpp
// car2: main.cpp car.cpp car.h
	g++ -I$(CARDIR)/include -L$(CARDOR)/lib -o car2 main.cpp -lcar
	//"sudo apt install make", type the previous line in the terminal
	// after typing that, then we can just type "make car" or "make"

	// "g++ c car.cpp"
	// "ls"
	// "ar -rcf libcar.a car.o", making a library for car
	// "ls"

	// Move include and lib to carlib file
	//
